server:
  port: '8090'

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    prefer-ip-address: true

spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/jhonatan-maza/bootcamp-gateway
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: bootcamp-customer
          uri: lb://bootcamp-customer
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        #routes[0]:
      #id: bootcamp-customer
        #predicates: Path=/customer/**
        #filters: StripPrefix=1
        #uri: lb://bootcamp-customer
        #routes[1]:
      #id: bootcamp-passive
        #predicates: Path=/passive/**
        #filters: StripPrefix=1
        #uri: lb://bootcamp-passive
        #routes[2]:
      #vid: bootcamp-active
        #predicates: Path=/active/**
        #filters: StripPrefix=1
        #uri: lb://bootcamp-active
        #routes[3]:
      #id: bootcamp-transaction
        #predicates: Path=/transaction/**
        #filters: StripPrefix=1
        #uri: lb://bootcamp-transaction
        #routes[4]:
      #id: openapi
        #uri: http://localhost:${server.port}
        #predicates: Path=/v3/api-docs/**
        #filters: StripPrefix=2
        #filters: RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
    loadbalancer:
      ribbon:
        enabled: false
  application:
    name: bootcamp-gateway

springdoc:
  swagger-ui:
    urls:
      - name: bootcamp-customer
        url: /bootcamp-customer/api-docs/