spring:
  cloud:
    gateway:
      routes[0]:
        id: bootcamp-customer
        predicates: Path=/customer/**
        filters: StripPrefix=1
        uri: lb://bootcamp-customer
      discovery:
        locator:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
  application:
    name: bootcamp-gateway

server:
  port: '8090'

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    prefer-ip-address: true
